persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
  mountPath: /var/lib/influxdb2
  subPath: ""
service:
  type: LoadBalancer
  port: 80
  targetPort: 8086
  annotations: {}
  labels: {}
  portName: http
